# app 的唯一 id,上架到商店需要保证不要冲突,尽量使用开发者自己的域名作为后缀.
package: cloud.lazycat.app.xiao.gitlab-ci-runner
# app 的版本
version: 0.0.1

# 软件名称,会显示在启动器之类的地方
name: GitLab CI Runner 管理器
keyword: gitlab,ci,cd,pipeline,devops,automation,continuous-integration,continuous-delivery,runner
description: GitLab CI Runner 管理器提供了一个简单易用的 Web 界面,用于管理多个 GitLab Runner。支持注册、启动、停止、查看日志等功能。

# 使用说明
usage: |
  当前 Runner 管理器仅支持 shell 模式的 Runner，更多模式敬请期待！

locales:
  zh:
    name: GitLab CI Runner 管理器
    description: 提供简单易用的 Web 界面管理多个 GitLab Runner
  en:
    name: GitLab CI Runner Manager
    description: Simple web interface for managing multiple GitLab Runners

# 软件本身的 license
license: Apache-2.0

# 软件的主页,会在商店等地方体现
homepage: https://github.com/lazycatapps/gitlab-ci-runner

# lpk 的作者,会在商店等地方体现
author: xiao

# application 作为一个特殊的 container 运行，对应的 service 名称为固定的`app`， 其他 service 可以通过此名称与 app 进行通讯
application:
  # 是否存在后台任务， 若存在则系统不会对此 app 进行主动休眠等操作
  background_task: true

  # 期望的 app 域名，如果系统中已经有对应域名则会提示用户选择其他域名。 最终 app 分配到的域名以/lzcapp/run/app.subdomain 为准
  subdomain: gitlab-ci-runner

  # HTTP 路由配置 - 转发到 gitlab-ci-runner 服务的 8098 端口
  routes:
    - /=http://gitlab-ci-runner:8098

  # 是否启用多实例模式
  multi_instance: false

  # GPU 加速支持
  gpu_accel: false

  # KVM 加速支持
  kvm_accel: false

  # USB 加速支持
  usb_accel: false

  # 健康检查配置
  health_check:
    test_url: http://gitlab-ci-runner:8098
    start_period: 10s
    disable: false

services:
  gitlab-ci-runner:
    # Docker 镜像 - 使用本地构建的镜像
    image: registry.lazycat.cloud/liu/lazycatapps/gitlab-ci-runner:c2ff5a58d21c9811

    # 环境变量配置
    environment:
      - CONFIG_DIR=/home/gitlab-runner/configs

    # 持久化目录绑定
    binds:
      # GitLab Runner 配置目录
      - /lzcapp/var/configs:/home/gitlab-runner/configs

    # 健康检查
    health_check:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8098
      start_period: 10s
      disable: false

# 不支持的平台
unsupported_platforms:
  - ios
  - android
